name = "bunasa-site"  # Replace with your desired project name
type = "javascript"  # Use 'javascript' for static sites or 'webpack' for webpack-based builds

account_id = "6ede5b8b1719d8b66235d1a95f59ffca"  # Your Cloudflare account ID
workers_dev = true  # Optional: If you're deploying to a worker dev environment (e.g., your-project-name.workers.dev)

# If using a custom domain, set it here:
# route = "bunasa.com/*"
# zone_id = "845ab32f38378fb71ccbe0422fba333d"  # Only needed for custom domains

[build]
command = ""  # Leave empty for static sites, or specify a build command if using a framework (e.g., "npm run build")
directory = "./"  # The directory containing your static files (use './' for the root directory)
