name: Bunasa-site

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloudflare Wrangler
        uses: cloudflare/wrangler-action@v2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Your Cloudflare API token

      - name: Publish to Cloudflare Pages
        run: |
          wrangler pages publish ./  # This publishes the current directory to Cloudflare Pages
