name: Deploy Static Site to Cloudflare

on:
  push:
    branches:
      - main  # Deploy on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare
        uses: cloudflare/github-actions@v2
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project-name: bunasa-site  # Name of your project
          directory: ./  # Path to the static site files (root directory)
