name: Deploy Static Site to Cloudflare Pages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v3  # Use the official Pages action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Your Cloudflare API Token stored in GitHub Secrets
          projectName: your-project-name  # The name of your Cloudflare Pages project
          directory: ./  # Directory containing your static files (use ./ if the files are in the root directory)
